# Generated by Django 4.1.3 on 2022-12-04 21:32

import bonuscards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.CharField(max_length=4, validators=[bonuscards.validators.validate_numbers], verbose_name='series')),
                ('card_number', models.CharField(max_length=12, validators=[bonuscards.validators.validate_numbers], verbose_name='number')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='release_date')),
                ('expire_date', models.DateTimeField(verbose_name='expire_date')),
                ('last_active_date', models.DateTimeField(blank=True, null=True, verbose_name='last_active_date')),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('NOT_ACTIVE', 'not active'), ('DEACTIVE', 'deactive')], default='NOT_ACTIVE', max_length=100)),
            ],
            options={
                'verbose_name': 'Bonus_Card',
                'ordering': ('release_date',),
                'unique_together': {('card_series', 'card_number')},
            },
        ),
    ]
