# Generated by Django 4.1.4 on 2022-12-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuscards', '0003_remove_bonuscard_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'ordering': ('-release_date',), 'verbose_name': 'Bonus_Card'},
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('total_price', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuscard', to='bonuscards.bonuscard')),
            ],
        ),
    ]
