# Generated by Django 4.1.4 on 2022-12-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuscards', '0005_alter_bonuscard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuscard',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('NOT ACTIVE', 'not active'), ('DEACTIVE', 'deactive')], default='NOT_ACTIVE', max_length=100, verbose_name='Статус'),
        ),
    ]
