# Generated by Django 4.1.4 on 2022-12-24 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonuscards', '0007_alter_bonuscard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата покупки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.CharField(max_length=200, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.IntegerField(verbose_name='Цена покупки'),
        ),
    ]
