# Generated by Django 4.1.4 on 2022-12-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuscards', '0008_purchase_date_alter_purchase_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuscard', to='bonuscards.bonuscard', verbose_name='Карта'),
        ),
    ]
